### ISSUE TITLE
RPC connection refused

### ISSUE THREAD

**Issue by gperezalba** [Alethio/memento#7]
Hi,

I'm following the steps for "Running Memento with Lite Explorer" and a problem appears when starting the blocktracker: it says connection refused to http://127.0.0.1:8545... I'm running my own PoA with Parity and the node is working properly (I can curl RPC methods).

However, I have another PoA with the RPC port in a https domain and when configuring the eth.rpc to the https domain it doesn't throw the error and works fine...

Any help is appreciated.

Guillermo

**Comment by kwix** [comment]
Hi Guillermo, 

Since you said you're following the steps for "Running Memento with Lite Explorer", I'm assuming you are trying to run memento in docker. 
In that case, the most probable cause is the container not having access to the host. 
If you are running the node on your host machine, try using the local ip address instead of `127.0.0.1` (in my case, it looks like this: `192.168.0.xxx`). 

Let me know if that works out for you.

**Comment by gperezalba** [comment]
Yeah! It solved the problem thanks @kwix 

And congrats for the good job you've done last months... last time I used the blockexplorer was in june and you've done a good change since then, well done guys!

**Comment by SalahAdDin** [comment]
I have the same problem adding a `ganache-cli` container to the compose file.
